config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resource :registration
  resource :session
  resource :password_reset
  resource :password

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "main#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true, uniqueness: true

  normalizes :email, with: ->email { email.strip }

  generates_token_for :password_reset, expires_in: 10.minutes do
    password_salt&.last(10)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  private

  def authenticate_user!
    if !user_signed_in?
      redirect_to new_session_path, alert: "You must be
      signed in to view this page."
    end
  end


  def current_user
    Current.user ||= authenticate_user_from_session
  end
  helper_method :current_user

  def authenticate_user_from_session
    if session[:user_id].present?
      User.find_by(id: session[:user_id])
    end
  end

  def user_signed_in?
    current_user.present?
  end
  helper_method :user_signed_in?

  def login(user)
    Current.user = user
    reset_session
    session[:user_id] = user.id
  end

  def logout
    Current.user = nil
    reset_session
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index

  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :set_user_by_token, only: [:edit, :update]

  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user
      PasswordMailer.with(
        user: user,
        token: user.generate_token_for(:password_reset)
      ).password_reset.deliver_later
    redirect_to root_url, notice: "Email sent with password reset instructions."
    else
      flash.now[:error] = "Email address not found."
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @user.update(password_params)
      redirect_to new_session_path, notice: "Password updated. Please sign in."
    else
      flash.now[:error] = "Password not updated."
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_user_by_token
    @user = User.find_by_token_for(:password_reset, params[:token])
    puts @user.inspect
    redirect_to new_password_reset_path, alert: "Invalid token." unless @user.present?
  end

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  before_action :authenticate_user!

  def edit
  end

  def update
    if current_user.update(password_params)
      redirect_to root_path, notice: "Password updated."
    else
      flash.now[:error] = "Password not updated."
      render :edit, status: :unprocessable_entity
    end
  end

  def create
    user = User.find_by_email(params[:email])
    if user
      user.send_password_reset
      redirect_to root_url, :notice => "Email sent with password reset instructions."
    else
      flash.now[:error] = "Email address not found."
      render 'new'
    end
  end

  private

  def password_params
    # user can edit the html to bypass the password challenge and rails will skip the validation if the password is nil
    params.require(:user).permit(:password_challenge, :password, :password_confirmation).with_defaults(password_challenge: "")
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login @user
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    if user = User.authenticate_by(email: params[:email], password: params[:password])
      login user
      redirect_to root_path
    else
      flash[:alert] = "Invalid email or password."
      redirect_to new_session_path, status: :unauthorized
    end
  end

  def destroy
    logout
    redirect_to root_path, notice: "You have been logged out."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsAuthenticationFromScratch</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div><%= notice %></div>
    <div><%= alert %></div>


    <% if user_signed_in? %>
      <div>
        Logged in as <%= current_user.email %>.
        <%= link_to "Edit password", edit_password_path %>
        <%= button_to "Log out", session_path, method: :delete %>
      </div>
    <% else %>
      <%= link_to "Sign up", new_registration_path %>
      <%= link_to "Log in", new_session_path %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/main/index.html.erb
<h1>Home Page</h1>

app/views/password_resets/edit.html.erb
<h1>Update Password</h1>

<%= form_with model: @user, url: password_reset_path(token: params[:token]) do |f| %>
  <% if f.object.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(f.object.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
        <% f.object.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div>
    <%= f.label :password %><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <div>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off" %>
  </div>

  <div>
    <%= f.submit "Reset Password" %>
  </div>
<% end %>

app/views/password_resets/new.html.erb
<h1>Forgot Password</h1>

<%= form_with model: @user, url: password_reset_path do |f| %>
  <div>
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true %>
  </div>

  <div>
    <%= f.submit "Reset Password" %>
  </div>
<% end %>